version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopdoda
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes: 
      - mysql-data:/var/lib/mysql
      - ./shopdoda.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: wada-spring:latest
    ports:
      - "8005:9090"
    depends_on: 
      - mysql
volumes: 
  mysql-data: